### PR TITLE
Avoid runtime method definitions

### PR DESCRIPTION
**Pull request by donaldong**
### Motivation
In ruby-prof reports, redefining methods in runtime creates quite a bit of overhead, especially in the situations where we need to coerce in batches. It'd be nice if the code can run faster.

### Approach
This adds a proxy-like class to handle the `.new` call. What happens under the hood is it's calling new on an instance, instead of `Class.new`. We hide this implementation from sorbet so it still works as before. This also removes the sigs on the method definitions.

### Test Plan
The tests cover the introduced changes. Generate the ruby-prof report again with the new code, see a ~30% performance improvement.

### CODE REVIEW

**Comment by donaldong** [comment]
simplify changes

:mag_right: [Click to see changes since last update](https://github.com/chanzuckerberg/sorbet-coerce/compare/4260419e23b97a15a8dc93d87bde7b956eefd80a..bf9894ca9c98c6d0405de87881dd2c5773ba81d5).

**Comment by manhhung741** [comment]
Nice fix. The .new fix is so deceptive. It’s a bit too hacky. Essentially
we trick sorbet to think that the method returns a class, but it actually
return an instance.

I wonder can we implement a converter “factory” in a different way that’s
less hacky. But if Class.new is what expensive, idk if we can do better.

**Comment by donaldong** [comment]
> But if Class.new is what expensive, idk if we can do better.

Yeah, I'm in favor of this hack to improve its performance. This is supposed to an internal implementation detail (and we've been deceiving sorbet statically anyway 🤷‍♂️)

**Comment by manhhung741** [comment]
We're living on the edge!

**Pull request merged**
