### PR TITLE
add `coerce_empty_to_nil` config for string conversion

### LINKED ISSUE #58: [Question] Accept PR for config flag on how to deal with empty strings
I would love a feature where an empty string is coerced into a nil value.

So something like this:

```ruby
TypeCoerce[T.nilable(String)].new.from('', coerce_empty_to_nil: true)
=> nil
```

This can be super useful when parsing request parameter (empty fields are passed in as an empty string)

Would you accept a PR like this?

### PR DESCRIPTION
**Pull request by leifg**
After clarifying in #58 seems to be a good config flag for coercing empty strings into nil.

Closes #58.

### CODE REVIEW

**Review by mattxwang — APPROVED** [review]
Thank you for the quick turnaround and your contribution @leifg! This seems pretty great to me, and I've had a chance to test this locally (as well as on CI - thanks for submitting the PR to resolve the issues with ruby 3+).

What are your thoughts on also adding a global configuration parameter, similar to `TypeCoerce::Configuration.raise_coercion_error`? No need to do this if you don't think it's necessary (for example, I'm not sure if it's relevant in your use-case of request parsing).

---

As an aside, I'll probably publish a new release of the gem after we merge this in. Hopefully you'll have a chance to test this soon!

**Comment by leifg** [comment]
> What are your thoughts on also adding a global configuration parameter, similar to `TypeCoerce::Configuration.raise_coercion_error`? No need to do this if you don't think it's necessary (for example, I'm not sure if it's relevant in your use-case of request parsing).

For me personally I don't see a use case. In addition: making something like a global flag could cause unwanted errors because you would get instances of TypeError where an empty string is fine.

**Comment by mattxwang** [comment]
> For me personally I don't see a use case. In addition: making something like a global flag could cause unwanted errors because you would get instances of TypeError where an empty string is fine.

Sounds good, just wanted to check in. Thanks again for your contribution, much appreciated!

**Comment by leifg** [comment]
> Sounds good, just wanted to check in. Thanks again for your contribution, much appreciated!

Of course! Always happy to help out.

**Pull request merged**
